import os
import sys
# Add parent directory to path to allow importing modules from backend
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
import asyncio
from dotenv import load_dotenv
from db_client import DBClient

# Load environment variables
load_dotenv()

def check_latest_task_source():
    db = DBClient()
    if not db.supabase:
        print("Error: Could not connect to Supabase. Check environment variables.")
        return

    try:
        # Fetch the latest task
        response = db.supabase.table("tasks").select("*").order("created_at", desc=True).limit(1).execute()
        if not response.data:
            print("No tasks found.")
            return

        task = response.data[0]
        task_id = task['id']
        video_url = task.get('video_url', 'Unknown URL')
        created_at = task.get('created_at', 'Unknown Time')

        print(f"Latest Task Found:")
        print(f"  ID: {task_id}")
        print(f"  URL: {video_url}")
        print(f"  Created At: {created_at}")

        # Fetch outputs
        outputs = db.get_task_outputs(task_id)
        
        script_raw_output = next((o for o in outputs if o['kind'] == 'script_raw'), None)
        
        if script_raw_output and script_raw_output.get('content'):
            try:
                content = json.loads(script_raw_output['content'])
                model = content.get('model', 'unknown')
                language = content.get('language', 'unknown')
                
                print(f"\nTranscript Source Analysis:")
                print(f"  Detected Model: {model}")
                print(f"  Detected Language: {language}")
                
                if "supadata" in model.lower():
                    print(f"\n==> RESULT: The transcript was fetched from the API (Supadata).")
                elif "whisper" in model.lower():
                    print(f"\n==> RESULT: The transcript was generated by us (OpenAI Whisper).")
                else:
                    print(f"\n==> RESULT: Unknown source (Model: {model})")
                    
            except json.JSONDecodeError:
                print("Error parsing script_raw content JSON.")
        else:
            print("No 'script_raw' output found or content is empty. Cannot determine source definitively.")
            # Fallback check: audio output
            audio_output = next((o for o in outputs if o['kind'] == 'audio'), None)
            if audio_output:
                 print("  (Audio output exists, which happens in both cases usually, but check content if needed)")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    check_latest_task_source()
